spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/sophub
spring.datasource.username=postgres
spring.datasource.password=Darkness228+
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
